version: "3.8"

services:
    danceagent-api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - "DB_USER=danceagent"
            - "DB_PASSWORD=${DB_PASSWORD}"
            - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
        ports:
            - "8080"
        labels:
            - "traefik.http.services.danceagent-api.loadbalancer.server.port=8080"
            - "traefik.http.routers.danceagent-api.rule=PathPrefix(`/danceagent-api`)"
            - "traefik.docker.network=traefik_default"
            - "traefik.http.routers.danceagent-api.middlewares=danceagent-api-stripprefix"
            - "traefik.http.middlewares.danceagent-api-stripprefix.stripprefix.prefixes=/danceagent-api"
        networks:
            - traefik_default
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
  traefik_default:
    external: true
    