version: "3.8"

services:
    danceagent-api:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - "DB_PASSWORD=${DB_ROOT_PASSWORD}"
            - "SPRING_PROFILES_ACTIVE=prod"
        labels:
            - "traefik.http.services.danceagent-api.loadbalancer.server.port=8080"
            - "traefik.http.routers.api.rule=PathPrefix(`/danceagent-api`)"
            - "traefik.http.routers.api.service=danceagent-api-danceagent@docker"
        networks:
            - bridge
            - internal
        depends_on:
            - db
    db:
        image: mariadb:10.7.1
        volumes:
            - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: danceagent
        networks:
            - internal

networks:
  bridge:
    external: true
  internal:
    external: false
    