spring:
  config:
    activate:
      on-profile: default

okta:
  oauth2:
    issuer: https://dev-00327502.okta.com/oauth2/default
    client-id: 0oa3eu8m79HimDYhO5d7
    pkce-always: true

datasource:
  url: jdbc:mysql://localhost:3306/danceagent?zeroDateTimeBehavior=CONVERT_TO_NULL
  user: root
  password: ^Free90Bird^